### ISSUE TITLE
How to run this application

### ISSUE THREAD

**Issue by Vishalbb27** [SwapnilSrkr/QuizApplication#1]
I cloned this repo, and I started to run. It failed!..

![image](https://user-images.githubusercontent.com/71935963/177261767-c9ec9dff-15ab-4a3b-8fe2-f494093cf05f.png)
![image](https://user-images.githubusercontent.com/71935963/177261816-64ef832b-43f1-4b0e-bc00-2b75eee13de5.png)

I tried to do Gradle sync again, but it didn't work.

**Comment by numanuddin1** [comment]
> 

set JDK location for this project
